### ISSUE TITLE
Api Auth Error

### ISSUE THREAD

**Issue by daraptoor** [GeekyAnts/laravel-lumen-jwt-boilerplate#1]
When ever i try to login or register this error coming up.

`{
    "message": "Class App\\Models\\User contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Tymon\\JWTAuth\\Contracts\\JWTSubject::getJWTIdentifier, Tymon\\JWTAuth\\Contracts\\JWTSubject::getJWTCustomClaims)",
    "code": 1,
    "status_code": 500
}`

**Comment by faizahmedfarooqui** [comment]
The JWT Trait was missing in the User's Model. I have added that now, can you please review this again.

**Comment by daraptoor** [comment]
yes it work.
